---
# tasks file for systemd_service

- name: "Install service file"
  template:
    src: "service.tpl"
    dest: "/etc/systemd/system/{{ service.name }}.service"

- name: "Enabled service {{service.name}}"
  systemd:
    daemon_reload: yes
    name: "{{service.name}}"
    enabled: yes

- name: "Start service {{service.name}}"
  systemd:
    name: "{{service.name}}"
    enabled: yes
    state: started
  when: start_service|bool